function regions = defineRegions()
%DEFINEREGIONS  The 6 northern-Israel map regions (shared by all configs).
%
%   regions = defineRegions()
%
%   Returns the region struct array used by both the legacy monolithic
%   pipeline (buildConfig) and the raytracing Part A (buildConfigA). Kept in
%   one place so the bboxes / placement discs / categories never drift apart.
%
%   Fields per region:
%     name                    short ident used in logs and result files
%     osm_path                repo-relative .osm file (empty => no OSM buildings)
%     latlim_override         [lo, hi] in degrees; [] means read from OSM
%     lonlim_override         [lo, hi] in degrees; [] means read from OSM
%     placement_diameter_km   per-region RX disk diameter (km):
%                               urban_suburban = 5 (2.5 km radius),
%                               others         = 10 (5 km radius)
%     category                'urban_suburban' or 'other' - drives the
%                              two-aggregate split in histograms / CCDFs

    % Urban/Suburban regions (~5x5 km bboxes; buildings available).
    % Relocated 2026-06-04 (old Nahariya site dropped) to a denser urban core
    % (centre 33.241578, 35.385281); buildings regenerated from Overture + nDSM.
    regions = struct('name','urban_suburban_01', ...
        'osm_path','', ...
        'latlim_override',[33.216553, 33.266603], ...
        'lonlim_override',[35.355371, 35.415191], ...
        'placement_diameter_km', 5, ...
        'category', 'urban_suburban');

    regions(end+1) = struct('name','urban_suburban_02', ...
        'osm_path','resources/osm/urban_suburban_02.osm', ...
        'latlim_override',[33.24621, 33.29188], ...
        'lonlim_override',[35.19915, 35.25377], ...
        'placement_diameter_km', 5, ...
        'category', 'urban_suburban');

    % Relocated 2026-06-04 to a denser/more-urban site (centre 33.171427,
    % 35.521378); buildings regenerated from Overture + nDSM for this bbox.
    regions(end+1) = struct('name','urban_suburban_03', ...
        'osm_path','', ...
        'latlim_override',[33.146402, 33.196452], ...
        'lonlim_override',[35.491468, 35.551288], ...
        'placement_diameter_km', 5, ...
        'category', 'urban_suburban');

    % Forest region (~10x10 km)
    regions(end+1) = struct('name','forest_01', ...
        'osm_path','', ...
        'latlim_override',[32.95132, 33.04470], ...
        'lonlim_override',[35.34572, 35.45705], ...
        'placement_diameter_km', 10, ...
        'category', 'other');

    % Mountain regions (~10x10 km)
    regions(end+1) = struct('name','mountain_01', ...
        'osm_path','', ...
        'latlim_override',[33.35397, 33.46077], ...
        'lonlim_override',[35.56332, 35.69125], ...
        'placement_diameter_km', 10, ...
        'category', 'other');

    regions(end+1) = struct('name','mountain_02', ...
        'osm_path','', ...
        'latlim_override',[33.44502, 33.54904], ...
        'lonlim_override',[35.79151, 35.91625], ...
        'placement_diameter_km', 10, ...
        'category', 'other');

    % (rural_open_01 dropped 2026-06-04 - region set is now 3 urban + 3
    %  open/mountainous: forest_01 + mountain_01 + mountain_02.)
end
