function exportSummaryHtml(cfg, results, axes_struct, out_path)
%EXPORTSUMMARYHTML  Bundle scenario summary + plot snapshots into one HTML.
%
%   exportSummaryHtml(cfg, results, axes_struct, out_path)
%
%   axes_struct  struct with axes handles to embed. Field name becomes the
%                section title; value is a uiaxes/axes handle.
%   out_path     destination .html (overwrites)
%
%   Plots are exported via exportgraphics() to temporary PNGs, then
%   embedded as base64 data URLs so the resulting HTML is self-contained.

    tmpdir = tempname; mkdir(tmpdir);
    cleanup = onCleanup(@() rmTmp(tmpdir));

    fields    = fieldnames(axes_struct);
    plot_b64  = strings(0, 1);
    plot_titles = strings(0, 1);
    for k = 1:numel(fields)
        ax = axes_struct.(fields{k});
        if isempty(ax) || ~isgraphics(ax), continue; end
        png_path = fullfile(tmpdir, sprintf('plot_%d.png', k));
        try
            exportAxesAsPng(ax, png_path);
        catch
            continue;
        end
        if ~isfile(png_path), continue; end
        plot_b64(end+1, 1)    = string(base64encodeBytes(png_path)); %#ok<AGROW>
        plot_titles(end+1, 1) = string(prettifyName(fields{k}));     %#ok<AGROW>
    end

    timestamp = string(datetime('now', 'Format', 'yyyy-MM-dd HH:mm'));
    [hero_html, kpi_html] = buildHero(cfg, results, timestamp);
    config_html  = buildConfigSections(cfg);
    regions_html = buildRegionsTable(results);
    plots_html   = buildPlotsHtml(plot_b64, plot_titles);

    css = inlineStyles();

    html = strcat( ...
        "<!doctype html><html lang=""en""><head><meta charset=""utf-8""/>", ...
        "<meta name=""viewport"" content=""width=device-width,initial-scale=1""/>", ...
        "<title>galuboy-sim &middot; scenario summary</title>", ...
        "<style>", css, "</style></head><body>", ...
        hero_html, ...
        "<main class=""container"">", ...
        kpi_html, ...
        "<section class=""card""><h2>Configuration</h2>", config_html, "</section>", ...
        "<section class=""card""><h2>Per-region results</h2>", regions_html, "</section>", ...
        "<section class=""card""><h2>Plots</h2>", plots_html, "</section>", ...
        "<footer><span>Generated by galuboy-sim &middot; ", timestamp, "</span></footer>", ...
        "</main></body></html>");

    fid = fopen(out_path, 'w');
    if fid < 0
        error('exportSummaryHtml:openFailed', 'Cannot write %s', out_path);
    end
    fwrite(fid, char(html), 'char');
    fclose(fid);
end


% =========================================================================
%  Hero header + KPI cards
% =========================================================================
function [hero_html, kpi_html] = buildHero(cfg, results, timestamp)
    region_name = '';
    overall_total = NaN;
    inf_total = NaN;
    veh_total = NaN;
    n_samples = 0;
    elapsed_s = 0;
    if numel(results) >= 1
        res = results(1);
        region_name = res.region.name;
        if ~isempty(res.available)
            [overall_total, inf_total, veh_total] = computeRates(res);
            n_samples = numel(res.available);
        end
        elapsed_s = res.elapsed_s;
    end

    hero_html = strcat( ...
        "<header class=""hero"">", ...
        "<div class=""hero-inner"">", ...
        "<div class=""brand"">galuboy<span>-sim</span></div>", ...
        "<h1>Scenario summary</h1>", ...
        "<p class=""subtitle"">", htmlEscape(region_name), ...
        "  &middot;  ", htmlEscape(timestamp), "</p>", ...
        "</div></header>");

    kpi_html = strcat( ...
        "<section class=""kpis"">", ...
        kpiCard("Overall availability", percentStr(overall_total), accentForRate(overall_total)), ...
        kpiCard("Infantry",             percentStr(inf_total),     accentForRate(inf_total)), ...
        kpiCard("Vehicular",            percentStr(veh_total),     accentForRate(veh_total)), ...
        kpiCard("Samples",              compactInt(n_samples),     "neutral"), ...
        kpiCard("Elapsed",              sprintf("%.1f s", elapsed_s), "neutral"), ...
        kpiCard("Availability target",  sprintf("%g%%", cfg.analysis.percentile), "neutral"), ...
        "</section>");
end


function html = kpiCard(label, value, accent)
    html = strcat( ...
        "<div class=""kpi kpi--", accent, """>", ...
        "<div class=""kpi-label"">", htmlEscape(label), "</div>", ...
        "<div class=""kpi-value"">", htmlEscape(value), "</div>", ...
        "</div>");
end


function s = percentStr(v)
    if isnan(v), s = "—"; else, s = string(sprintf('%.1f%%', 100*v)); end
end


function s = accentForRate(v)
    if isnan(v),       s = "neutral";
    elseif v >= 0.85,  s = "good";
    elseif v >= 0.6,   s = "warn";
    else,              s = "bad";
    end
end


function s = compactInt(n)
    if n >= 1e6,      s = string(sprintf('%.1fM', n/1e6));
    elseif n >= 1e3,  s = string(sprintf('%.1fk', n/1e3));
    else,             s = string(sprintf('%d', n));
    end
end


% =========================================================================
%  Configuration sections (grouped)
% =========================================================================
function html = buildConfigSections(cfg)
    groups = {
        'Transmitter', {
            'Frequency',          sprintf('%.3f MHz', cfg.tx.frequency_hz/1e6)
            'Power (air, DL)',    sprintf('%.1f dBm',  cfg.tx.power_air_dbm)
            'Power (gnd, UL)',    sprintf('%.1f dBm',  cfg.tx.power_gnd_dbm)
            'Altitude (target)',  formatTxAltitude(cfg.tx)
            'Airborne antenna',   cfg.tx.airborne.antenna_name
            'Ground   antenna',   cfg.tx.ground.antenna_name
        }
        'Receivers', {
            'Infantry',          sprintf('%d  &middot;  %.1f m  &middot;  %s', cfg.rx.infantry.count,  cfg.rx.infantry.height_m,  cfg.rx.infantry.antenna_name_dl)
            'Vehicular',         sprintf('%d  &middot;  %.1f m  &middot;  %s', cfg.rx.vehicular.count, cfg.rx.vehicular.height_m, cfg.rx.vehicular.antenna_name_dl)
            'Airborne RX (UL)',  cfg.rx.airborne.antenna_name_ul
            'Placement radius',  sprintf('%.2f km', cfg.rx.placement_radius_km)
        }
        'Propagation', propagationRows(cfg)
        'Analysis', {
            'Threshold',          sprintf('%.1f dBm', cfg.analysis.threshold_dbm)
            'Availability target',sprintf('%g%%', cfg.analysis.percentile)
            'Fade margin',        sprintf('%.1f dB', cfg.analysis.fade_margin_db)
        }
        'Flight', {
            'Steps',              sprintf('%d', cfg.flight.num_flight_steps)
            'Rotations',          sprintf('%d', cfg.flight.num_rotations)
            'Lemniscate length',  sprintf('%.0f m', cfg.flight.lemniscate_length_m)
            'Max tilt',           sprintf('%g&deg;', cfg.flight.max_tilt_deg)
        }
    };

    parts = strings(size(groups, 1), 1);
    for g = 1:size(groups, 1)
        rows_html = "";
        rows = groups{g, 2};
        for r = 1:size(rows, 1)
            rows_html = rows_html + strcat( ...
                "<dt>", htmlEscape(rows{r,1}), "</dt>", ...
                "<dd>", string(rows{r,2}), "</dd>");
        end
        parts(g) = strcat( ...
            "<div class=""cfg-group"">", ...
            "<h3>", htmlEscape(groups{g, 1}), "</h3>", ...
            "<dl>", rows_html, "</dl>", ...
            "</div>");
    end
    html = strcat("<div class=""cfg-grid"">", strjoin(parts, ""), "</div>");
end


% =========================================================================
%  Per-region results table
% =========================================================================
function html = buildRegionsTable(results)
    rows_html = "";
    for r = 1:numel(results)
        res = results(r);
        if isempty(res.available)
            rows_html = rows_html + strcat( ...
                "<tr><td>", htmlEscape(res.region.name), ...
                "</td><td colspan=""5"" class=""muted"">no data</td></tr>");
            continue;
        end
        [overall, inf_av, veh_av] = computeRates(res);
        rows_html = rows_html + strcat( ...
            "<tr>", ...
            "<td><strong>", htmlEscape(res.region.name), "</strong></td>", ...
            "<td>", string(numel(res.available)), "</td>", ...
            "<td>", rateBadge(overall), "</td>", ...
            "<td>", rateBadge(inf_av), "</td>", ...
            "<td>", rateBadge(veh_av), "</td>", ...
            "<td>", string(sprintf('%.1f s', res.elapsed_s)), "</td>", ...
            "</tr>");
    end
    html = strcat( ...
        "<table class=""regions"">", ...
        "<thead><tr>", ...
        "<th>Region</th><th>Samples</th>", ...
        "<th>Overall</th><th>Infantry</th><th>Vehicular</th><th>Elapsed</th>", ...
        "</tr></thead><tbody>", rows_html, "</tbody></table>");
end


function html = rateBadge(v)
    if isnan(v)
        html = "<span class=""muted"">&mdash;</span>";
        return;
    end
    cls = "badge badge--" + accentForRate(v);
    html = strcat("<span class=""", cls, """>", percentStr(v), "</span>");
end


% =========================================================================
%  Plots gallery
% =========================================================================
function html = buildPlotsHtml(b64s, titles)
    if isempty(b64s)
        html = "<p class=""muted"">No plots available.</p>";
        return;
    end
    items = strings(numel(b64s), 1);
    for k = 1:numel(b64s)
        items(k) = strcat( ...
            "<figure class=""plot"">", ...
            "<figcaption>", htmlEscape(titles(k)), "</figcaption>", ...
            "<div class=""plot-body"">", ...
            "<img src=""data:image/png;base64,", b64s(k), """ alt=""", htmlEscape(titles(k)), """/>", ...
            "</div></figure>");
    end
    html = strcat("<div class=""plots-grid"">", strjoin(items, ""), "</div>");
end


% =========================================================================
%  Per-RX-type rate
% =========================================================================
function s = formatTxAltitude(tx)
    if isfield(tx, 'altitude_msl_m') && ~isempty(tx.altitude_msl_m)
        s = sprintf('%.0f m MSL', tx.altitude_msl_m);
    else
        s = sprintf('%.0f m AGL at centroid', tx.altitude_m);
    end
end


function rows = propagationRows(cfg)
    p = cfg.propagation;
    model_label = prettyModelName(p.model);
    rows = {
        'Model',     model_label
        'Bandwidth', sprintf('%.2f kHz', p.bandwidth_hz/1e3)
        'Terrain',   ternary(p.use_terrain, ...
                             sprintf('DT2 &middot; <em>%s</em>', htmlEscape(p.terrain_name)), ...
                             'GMTED2010 (default)')
    };
    if strcmpi(char(p.model), 'longley-rice')
        if isfield(p, 'time_variability')
            rows(end+1, :) = {'Time variability tol.', ...
                sprintf('%.3f', p.time_variability)};
        end
        if isfield(p, 'situation_variability')
            rows(end+1, :) = {'Situation variability tol.', ...
                sprintf('%.3f', p.situation_variability)};
        end
    end
end


function s = prettyModelName(raw)
    s = char(raw);
    switch lower(s)
        case 'longley-rice', s = 'Longley-Rice (ITM)';
        case 'freespace',    s = 'Free-space (Friis)';
        case 'gas',          s = 'Atmospheric gas absorption';
        case 'rain',         s = 'Rain attenuation';
        case 'fog',          s = 'Fog/cloud attenuation';
        case 'tirem',        s = 'TIREM';
        case 'close-in',     s = 'Close-in (mmWave)';
    end
end


function [overall, inf_av, veh_av] = computeRates(res)
    M = size(res.available, 1);
    n_rx = size(res.available, 2);
    overall = mean(res.available(:));
    is_inf = false(M, n_rx);
    for m = 1:M
        col = res.rx_types{m};
        if iscategorical(col)
            row = (col == 'infantry');
        else
            row = strcmp(string(col), "infantry");
        end
        is_inf(m, :) = row(:).';
    end
    if any(is_inf(:)),  inf_av = mean(res.available(is_inf));   else, inf_av = NaN; end
    if any(~is_inf(:)), veh_av = mean(res.available(~is_inf));  else, veh_av = NaN; end
end


% =========================================================================
%  Helpers
% =========================================================================
function out = ternary(cond, a, b)
    if cond, out = a; else, out = b; end
end


function s = htmlEscape(in)
    s = char(string(in));
    s = strrep(s, '&', '&amp;');
    s = strrep(s, '<', '&lt;');
    s = strrep(s, '>', '&gt;');
    s = strrep(s, '"', '&quot;');
    s = string(s);
end


function name = prettifyName(raw)
    name = regexprep(char(raw), '([a-z])([A-Z])', '$1 $2');
end


function b64 = base64encodeBytes(file_path)
    fid = fopen(file_path, 'r');
    bytes = fread(fid, Inf, '*uint8');
    fclose(fid);
    b64 = matlab.net.base64encode(bytes);
end


function exportAxesAsPng(ax, png_path)
    % Temporarily force a white plot area (uiaxes default to a dark theme
    % in uifigure tabs which exports to a black PNG). Restore on exit.
    saved.color    = ax.Color;
    saved.xcolor   = ax.XColor;
    saved.ycolor   = ax.YColor;
    saved.gridcol  = ax.GridColor;
    saved.titcol   = ax.Title.Color;
    saved.xlblcol  = ax.XLabel.Color;
    saved.ylblcol  = ax.YLabel.Color;
    leg = [];
    if ~isempty(ax.Legend)
        leg = ax.Legend;
        saved.leg_color     = leg.Color;
        saved.leg_textcolor = leg.TextColor;
        saved.leg_edgecolor = leg.EdgeColor;
    end
    cleaner = onCleanup(@() restore(ax, leg, saved));

    ink = [0.15 0.15 0.18];
    ax.Color       = 'white';
    ax.XColor      = ink;
    ax.YColor      = ink;
    ax.GridColor   = [0.85 0.85 0.88];
    ax.Title.Color    = ink;
    ax.XLabel.Color   = ink;
    ax.YLabel.Color   = ink;
    if ~isempty(leg)
        leg.Color     = 'white';
        leg.TextColor = ink;
        leg.EdgeColor = [0.85 0.85 0.88];
    end

    try
        exportgraphics(ax, png_path, 'Resolution', 180, ...
            'BackgroundColor', 'white', 'Padding', 'tight');
    catch
        % R2022b and earlier don't support 'Padding' — fall back, then
        % crop white margins ourselves so the plot fills the card.
        exportgraphics(ax, png_path, 'Resolution', 180, 'BackgroundColor', 'white');
    end
    autoCropWhite(png_path);
end


function autoCropWhite(png_path)
    if ~isfile(png_path), return; end
    try
        img = imread(png_path);
    catch
        return;
    end
    if size(img, 3) > 3, img = img(:, :, 1:3); end
    is_bg = all(img > 245, 3);
    rows_keep = find(any(~is_bg, 2));
    cols_keep = find(any(~is_bg, 1));
    if isempty(rows_keep) || isempty(cols_keep), return; end
    pad = 6;
    r1 = max(1, rows_keep(1)   - pad);
    r2 = min(size(img, 1), rows_keep(end) + pad);
    c1 = max(1, cols_keep(1)   - pad);
    c2 = min(size(img, 2), cols_keep(end) + pad);
    imwrite(img(r1:r2, c1:c2, :), png_path);
end


function restore(ax, leg, saved)
    if ~isgraphics(ax), return; end
    ax.Color       = saved.color;
    ax.XColor      = saved.xcolor;
    ax.YColor      = saved.ycolor;
    ax.GridColor   = saved.gridcol;
    ax.Title.Color    = saved.titcol;
    ax.XLabel.Color   = saved.xlblcol;
    ax.YLabel.Color   = saved.ylblcol;
    if ~isempty(leg) && isgraphics(leg)
        leg.Color     = saved.leg_color;
        leg.TextColor = saved.leg_textcolor;
        leg.EdgeColor = saved.leg_edgecolor;
    end
end


function rmTmp(tmpdir)
    if isfolder(tmpdir)
        rmdir(tmpdir, 's');
    end
end


% =========================================================================
%  Inline CSS (kept compact)
% =========================================================================
function css = inlineStyles()
    css = string(join({
        ':root{'
        '  --bg:#f6f7fb;--surface:#ffffff;--ink:#15171c;--muted:#5b6373;'
        '  --line:#e6e8ee;--accent:#5a4ef7;--accent-2:#21d4a3;'
        '  --good:#1a8a5d;--good-bg:#d8f4e7;'
        '  --warn:#a06a00;--warn-bg:#fbe8c4;'
        '  --bad:#b1322a;--bad-bg:#fbdedb;'
        '  --neutral:#3a3f4a;--neutral-bg:#eef0f5;'
        '  --shadow:0 1px 2px rgba(20,22,30,0.05),0 6px 18px rgba(20,22,30,0.06);'
        '  --radius:14px;'
        '}'
        '*{box-sizing:border-box}'
        'html,body{margin:0;padding:0}'
        'body{background:var(--bg);color:var(--ink);'
        '  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif;'
        '  font-size:14.5px;line-height:1.5;-webkit-font-smoothing:antialiased;'
        '}'
        'h1,h2,h3{margin:0;letter-spacing:-0.01em}'
        'h1{font-size:30px;font-weight:700}'
        'h2{font-size:18px;font-weight:600;margin-bottom:14px}'
        'h3{font-size:13px;font-weight:600;color:var(--muted);text-transform:uppercase;letter-spacing:0.06em;margin-bottom:8px}'
        '.muted{color:var(--muted)}'
        ''
        '/* Hero */'
        '.hero{background:linear-gradient(135deg,#0e0f1a 0%,#1f2138 55%,#3b2a85 100%);color:#fff;padding:48px 24px 40px}'
        '.hero-inner{max-width:1180px;margin:0 auto}'
        '.brand{font-weight:700;letter-spacing:0.04em;text-transform:uppercase;font-size:13px;color:#bcb6f6;margin-bottom:22px}'
        '.brand span{color:var(--accent-2)}'
        '.hero h1{color:#fff;font-size:34px}'
        '.subtitle{margin:6px 0 0;color:#bbc0d4;font-size:15px}'
        ''
        '/* Layout */'
        '.container{max-width:1180px;margin:-24px auto 48px;padding:0 24px;display:flex;flex-direction:column;gap:20px}'
        '.card{background:var(--surface);border-radius:var(--radius);padding:24px;box-shadow:var(--shadow)}'
        ''
        '/* KPIs */'
        '.kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}'
        '@media (max-width:900px){.kpis{grid-template-columns:repeat(3,1fr)}}'
        '@media (max-width:560px){.kpis{grid-template-columns:repeat(2,1fr)}}'
        '.kpi{background:var(--surface);border-radius:var(--radius);padding:16px;box-shadow:var(--shadow);position:relative;overflow:hidden}'
        '.kpi:before{content:"";position:absolute;top:0;left:0;width:100%;height:3px;background:var(--neutral)}'
        '.kpi--good:before{background:var(--good)}'
        '.kpi--warn:before{background:var(--warn)}'
        '.kpi--bad:before{background:var(--bad)}'
        '.kpi--neutral:before{background:var(--accent)}'
        '.kpi-label{color:var(--muted);font-size:12px;font-weight:500;text-transform:uppercase;letter-spacing:0.05em}'
        '.kpi-value{font-size:24px;font-weight:700;margin-top:6px;letter-spacing:-0.01em}'
        ''
        '/* Config grid */'
        '.cfg-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:18px}'
        '.cfg-group{background:#fafbfd;border:1px solid var(--line);border-radius:10px;padding:14px 16px}'
        '.cfg-group dl{margin:0;display:grid;grid-template-columns:auto 1fr;gap:6px 14px}'
        '.cfg-group dt{color:var(--muted);font-weight:500;font-size:13px}'
        '.cfg-group dd{margin:0;font-variant-numeric:tabular-nums}'
        ''
        '/* Regions table */'
        'table.regions{width:100%;border-collapse:separate;border-spacing:0;font-variant-numeric:tabular-nums}'
        'table.regions th,table.regions td{padding:10px 12px;text-align:left;border-bottom:1px solid var(--line);font-size:14px}'
        'table.regions thead th{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:0.05em;background:#fafbfd}'
        'table.regions tbody tr:last-child td{border-bottom:none}'
        ''
        '/* Badges */'
        '.badge{display:inline-block;padding:2px 9px;border-radius:999px;font-size:12.5px;font-weight:600;font-variant-numeric:tabular-nums}'
        '.badge--good{color:var(--good);background:var(--good-bg)}'
        '.badge--warn{color:var(--warn);background:var(--warn-bg)}'
        '.badge--bad{color:var(--bad);background:var(--bad-bg)}'
        '.badge--neutral{color:var(--neutral);background:var(--neutral-bg)}'
        ''
        '/* Plots */'
        '.plots-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:18px}'
        '.plots-grid > *{min-width:0;min-height:0}'
        '.plot{margin:0;background:#fff;border:1px solid var(--line);border-radius:12px;overflow:hidden;display:flex;flex-direction:column}'
        '.plot figcaption{font-size:13px;font-weight:600;padding:10px 14px;background:#fafbfd;border-bottom:1px solid var(--line);color:var(--ink)}'
        '.plot-body{display:flex;align-items:center;justify-content:center;background:#fff;padding:6px}'
        '.plot img{display:block;width:100%;max-width:100%;height:auto;object-fit:contain}'
        ''
        '/* Footer */'
        'footer{margin:30px 0 0;text-align:center;color:var(--muted);font-size:12.5px}'
        ''
        '/* Print */'
        '@media print{'
        '  .hero{background:#1f2138 !important;-webkit-print-color-adjust:exact;print-color-adjust:exact}'
        '  .card,.kpi{box-shadow:none;border:1px solid var(--line)}'
        '  body{background:#fff}'
        '}'
    }, ''));
end
